### ISSUE TITLE
cyclogram in sandbox

### ISSUE THREAD

**Issue by wibeasley** [andkov/project-agrus#1]
plot events's start & stop time (y axis) by the date (x axis)

current look:

![cyclogram](https://github.com/andkov/project-agrus/blob/main/manipulation/sandbox/cyclogram.png?raw=true)

**Comment by wibeasley** [comment]
@andkov, these colors add a lot for me (check out the diff in the previous commit).  I tried to use the color picker on images like https://www.christies.com/en/lot/lot-5388667, but the shades were too gray.  Feel free to play around with them

**Comment by andkov** [comment]
Updated look (with Ukrainian annotations) 

![cyclogram](https://user-images.githubusercontent.com/2608073/160490675-6c7eb4cd-0bdc-4392-9c82-a9480f7f6fde.png)

I really like the idea of the double row of numbers in the bottom, but I'm not convinced it offers more than it takes. I hope we'll get to do some hairsplitting.
