### ISSUE TITLE
config files for multiple languages

### ISSUE THREAD

**Issue by wibeasley** [andkov/project-agrus#7]
I'm going to experiment with nested config files to support multiple languages.  Ideally the ggplot code doesn't change or care.  Just pulls from the directed yaml file.

**Comment by wibeasley** [comment]
I think our approach with [config's inheritance](https://github.com/rstudio/config#defaults-and-inheritance) feature is a good fit for our relatively repo (ie, just a few static graphs within an Rmd).  I found these alternative approaches while surveying the field.  At least one of these seems to call a webservice that translates on the fly.  @andkov, you might revisit this list for future projects or if this gets a lot more complex

* https://shi18ny.datasketch.dev/ & https://appsilon.com/rapid-internationalization-of-shiny-apps-shiny-i18n-version-0-2/
* https://appsilon.com/rapid-internationalization-of-shiny-apps-shiny-i18n-version-0-2/#introduction (similar name as bullet above, but different package & approach)
* These two build on the [i18n](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n).  Also see https://lingoport.com/what-is-i18n/
* https://www.r-bloggers.com/2014/11/another-take-on-building-a-multi-lingual-shiny-app/
* https://stackoverflow.com/questions/46017819/r-shiny-app-internationalization

**Comment by wibeasley** [comment]
I guess we have a few options for leveraging the config file.  One is to pull out the graph in a function that takes the language/config as a parameter.  Another is each html file has its own language, which probably means we use [rmarkdown's report parameterization](https://bookdown.org/yihui/rmarkdown/parameterized-reports.html).

@andkov, once you specify the English title & subtitle, I think this issue can be closed.  I just did some brainless text alignment, so make sure you pull those changes or the merge conflicts will be tedious.

```yaml
  title   : "**Title**"
  subtitle: "**Subtitle**"
```

I'm thinking of other languages we can recruit friend for.  I can easily get native speakers of Chinese, Spanish, French, & Norwegian.  I'm sure you could get (or do yourself) languages close to the region like Polish & Russian.  It probably makes sense to wait until the graph is finished maturing.

**Comment by andkov** [comment]
> I think our approach with [config's inheritance](https://github.com/rstudio/config#defaults-and-inheritance) feature is a good fit for our relatively repo (ie, just a few static graphs within an Rmd). I found these alternative approaches while surveying the field. At least one of these seems to call a webservice that translates on the fly. @andkov, you might revisit this list for future projects or if this gets a lot more complex
> 
> * https://shi18ny.datasketch.dev/ & https://appsilon.com/rapid-internationalization-of-shiny-apps-shiny-i18n-version-0-2/
> * https://appsilon.com/rapid-internationalization-of-shiny-apps-shiny-i18n-version-0-2/#introduction (similar name as bullet above, but different package & approach)
> * These two build on the [i18n](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n).  Also see https://lingoport.com/what-is-i18n/
> * https://www.r-bloggers.com/2014/11/another-take-on-building-a-multi-lingual-shiny-app/
> * https://stackoverflow.com/questions/46017819/r-shiny-app-internationalization

I like this (cofig) solution a lot. I was thinking of creating an object inside .Rmd session that would govern the application of needed labels, but this solution is much more elegant.

**Comment by andkov** [comment]
> I guess we have a few options for leveraging the config file. One is to pull out the graph in a function that takes the language/config as a parameter. Another is each html file has its own language, which probably means we use [rmarkdown's report parameterization](https://bookdown.org/yihui/rmarkdown/parameterized-reports.html).
> 
> @andkov, once you specify the English title & subtitle, I think this issue can be closed. I just did some brainless text alignment, so make sure you pull those changes or the merge conflicts will be tedious.
> 
> ```yaml
>   title   : "**Title**"
>   subtitle: "**Subtitle**"
> ```
> 
> I'm thinking of other languages we can recruit friend for. I can easily get native speakers of Chinese, Spanish, French, & Norwegian. I'm sure you could get (or do yourself) languages close to the region like Polish & Russian. It probably makes sense to wait until the graph is finished maturing.

With respect to maturation, I think we'll need to start chunking up the graph as the number of days grows.  Maybe 30 days per canvas? Maybe 60?  Then, it will be a sequence of graphs, so a dedicated HTML will serve as an output, one per language.  But again, you are right = the design will be dictated by the total number of days, so we may need to adjust as we go along.  Hope we won't get to deal with that.

**Comment by andkov** [comment]
The config is stable
